import type { FactionDef } from '../engine/types';

export const factions: FactionDef[] = [
  {
    id: 'ashen-veil',
    name: 'Order of the Ashen Veil',
    description:
      'A death-worshipping religious order whose monasteries rise from the burial fields like blackened teeth. The Ashen Veil tends the passage between worlds with solemn ceremony, believing that death is not an end but the truest sacrament — the moment when mortal dross burns away and the soul stands naked before eternity. Their priests wear funerary ash on their brows and speak in the cadences of last rites, even in casual conversation.',
    tags: ['death', 'ritual', 'order'],
    attitude: {
      death: 15,
      bone: 10,
      spirit: 10,
      ritual: 12,
      grave: 18,
      gravekeeper: 10,
      sanctity: 8,
      blood: -12,
      noble: -5,
      shadow: -8,
      relic: 0,
      oath: 3,
      cunning: -6,
      scavenger: -10,
      tomb: -4,
    },
    standingThresholds: {
      hostile: -50,
      feared: -25,
      distrusted: -10,
      neutral: 10,
      known: 25,
      respected: 50,
      allied: 75,
      devoted: 90,
    },
    lore: 'The Order was founded in the aftermath of the Pallid Catastrophe, when a wave of uncontrolled necromantic energy swept the moorlands and the dead rose in numbers that threatened to overwhelm the living. A wandering priest named Vael Ashborn walked into the heart of the catastrophe and emerged seven days later, hair white as cremation ash, carrying a doctrine written on strips of grave-linen. The dead, Vael taught, are not enemies to be fought nor tools to be exploited — they are congregants in the oldest church, and the living who tend them perform the holiest work. The Order has grown into a formidable institution, its chapels and ossuaries found wherever the dead rest uneasy. They view grave cultivation as sacred practice and blood magic as a vulgar perversion — the spilling of life-force for temporal power, when life-force should be surrendered willingly to the great passage. Those who earn the Order\'s devotion find doors opened in every cemetery and catacomb across the moorlands. Those who earn their wrath find that the dead have very long memories.',
  },

  {
    id: 'crimson-court',
    name: 'Crimson Court',
    description:
      'A blood nobility that rules from veiled palaces, their power flowing through cultivated bloodlines refined over centuries of selective marriage, ritual communion, and forbidden inheritance rites. The Crimson Court views cultivation as a birthright — something carried in the blood, not earned through labor or devotion. They are patrons of art and cruelty in equal measure, hosting lavish gatherings where the wine is never quite the color it should be.',
    tags: ['blood', 'noble', 'power'],
    attitude: {
      blood: 18,
      noble: 15,
      scion: 12,
      power: 10,
      shadow: 5,
      cunning: 6,
      death: -10,
      bone: -8,
      gravekeeper: -14,
      ritual: -3,
      grave: -12,
      oath: 0,
      iron: -4,
      relic: 3,
      spirit: -6,
    },
    standingThresholds: {
      hostile: -50,
      feared: -25,
      distrusted: -10,
      neutral: 10,
      known: 25,
      respected: 50,
      allied: 75,
      devoted: 90,
    },
    lore: 'The first Crimson Lords were warlords who discovered that the blood of defeated cultivators could be consumed to steal fragments of their power. Over generations, this crude practice was refined into an elaborate system of bloodline cultivation — selective breeding, ritual transfusion, and the maintenance of vast blood-reserves drawn from willing (and unwilling) donors. The Court\'s genealogies are their most guarded secrets, tracing lines of power back to pre-human sources that the archivists refuse to name in full. They regard death-work as peasant superstition — grubbing in the dirt among corpses when one could be refining the living essence that flows through noble veins. Relic hunters they tolerate, as old artifacts sometimes contain crystallized blood-essence worth harvesting. The Oathsworn they view with bemused contempt: admirable discipline, wasted on a commoner\'s framework. To earn a seat at the Crimson Court is to enter a world of intoxicating power and exquisite danger, where every toast might be a test and every gift carries the weight of obligation.',
  },

  {
    id: 'hollow-watch',
    name: 'Hollow Watch',
    description:
      'A militant order of wardens sworn to guard the boundary between life and death, ensuring that what passes through does so in the proper direction. The Hollow Watch maintains fortress-waypoints along the borders of blighted regions, their iron-clad sentinels standing vigil against incursions from both sides of the veil. They trust in oaths, duty, and the weight of forged steel above all forms of cultivation.',
    tags: ['oath', 'guard', 'iron'],
    attitude: {
      oath: 16,
      iron: 14,
      guard: 15,
      will: 12,
      warrior: 8,
      wanderer: 5,
      death: -10,
      bone: -12,
      spirit: -14,
      blood: -10,
      shadow: -16,
      noble: -3,
      grave: -8,
      ritual: -4,
      relic: 2,
      cunning: -2,
      scavenger: -5,
    },
    standingThresholds: {
      hostile: -50,
      feared: -25,
      distrusted: -10,
      neutral: 10,
      known: 25,
      respected: 50,
      allied: 75,
      devoted: 90,
    },
    lore: 'The Hollow Watch predates both the Order of the Ashen Veil and the Crimson Court, tracing its founding to the first mortal who hammered a blade from cold iron and swore to stand between the living and the things that hunger beyond the veil. They are not cultivators in the traditional sense — their power comes from oaths that bind their very souls to purpose, hardening their bodies and sharpening their wills until they become living bulwarks against the unnatural. The Watch views all cultivation that blurs the boundary between life and death with deep suspicion. Death cultivators disturb what should rest. Blood cultivators drink what should flow naturally. Shadow walkers tread paths that should remain untrodden. The Watch tolerates these practitioners only so long as they do not threaten the integrity of the boundary. When tolerance ends, the Watch responds with the certainty of a closing gate. Their fortress-waypoints are staffed by wardens who have taken the Threefold Oath: to hold, to endure, to never retreat. Those who break this oath are stripped of their iron and cast out, their names struck from the Watch\'s rolls with such finality that even their shadows seem to thin.',
  },
];
