import type { Origin } from '../engine/types';

export const origins: Origin[] = [
  {
    id: 'gravekeepers-apprentice',
    name: "Gravekeeper's Apprentice",
    description:
      'You were raised in the shadow of the ossuaries, where the dead outnumber the living a thousandfold. Your master taught you to read the whispers etched into old bones and to tend the passage between worlds with steady hands. The burial rites are second nature to you — the washing of remains, the sealing of restless spirits, the quiet negotiations with things that linger past their time.',
    tags: ['death', 'bone', 'spirit', 'ritual', 'gravekeeper'],
    startingTraits: ['death-touched'],
    startingMethods: ['grave-sense'],
    startingItems: ['ritual-knife'],
    startingResources: {
      vitality: 8,
      maxVitality: 8,
      essence: 12,
      maxEssence: 12,
      focus: 10,
      maxFocus: 10,
      stability: 14,
      maxStability: 14,
      momentum: 0,
      reputation: 0,
      materials: {},
    },
    affinities: ['death', 'bone', 'spirit'],
    lore: 'The gravekeepers of the Pallid Reaches are neither mourners nor necromancers — they are custodians of the threshold. Their apprentices learn that death is not an ending but a transformation, and that the bones of the departed hold the memory of every breath they ever drew. Those who serve among the tombs long enough begin to see the faint silver threads that bind spirit to remains, and in time, they learn to pluck those threads like the strings of a funerary harp.',
  },

  {
    id: 'outcast-blood-scion',
    name: 'Outcast Blood Scion',
    description:
      'Noble blood runs through your veins — blood that remembers power, blood that hungers. You were cast out from your house for reasons spoken only in whispers: a forbidden communion, a manifested gift that frightened even the elder cultivators. Now you walk alone, but the inheritance in your veins will not be denied. It pulses when danger is near, warms when opportunity presents itself, and sometimes, in the dark hours, it speaks.',
    tags: ['blood', 'noble', 'shadow', 'exile', 'scion'],
    startingTraits: ['noble-blood'],
    startingMethods: ['vein-furnace-breathing'],
    startingItems: ['blood-phial'],
    startingResources: {
      vitality: 10,
      maxVitality: 10,
      essence: 14,
      maxEssence: 14,
      focus: 8,
      maxFocus: 8,
      stability: 10,
      maxStability: 10,
      momentum: 0,
      reputation: 2,
      materials: {},
    },
    affinities: ['blood', 'noble', 'shadow'],
    lore: 'The great houses cultivate their bloodlines as carefully as their techniques — each generation refining the vital essence that flows through the family tree. But sometimes the blood remembers older pacts, stranger bargains struck in ages when the boundary between human and something else was thinner. A Blood Scion who manifests these atavistic gifts is both treasure and threat. Most are quietly disappeared. The ones who survive their exile carry within them the seed of a power that predates the houses themselves.',
  },

  {
    id: 'wandering-oathsworn',
    name: 'Wandering Oathsworn',
    description:
      'You are bound. Not by chains or contracts, but by words spoken in a place where words have weight — where a vow carves itself into the marrow of your soul. The oaths you carry are ancient, inherited from a line of sworn wanderers who walk the roads between settlements, upholding justice where no authority reaches. Your body is hard as hammered iron. Your will does not bend.',
    tags: ['oath', 'iron', 'will', 'wanderer', 'warrior'],
    startingTraits: ['oathbound'],
    startingMethods: ['oath-tempering'],
    startingItems: ['iron-tonic'],
    startingResources: {
      vitality: 14,
      maxVitality: 14,
      essence: 8,
      maxEssence: 8,
      focus: 10,
      maxFocus: 10,
      stability: 12,
      maxStability: 12,
      momentum: 0,
      reputation: 1,
      materials: {},
    },
    affinities: ['oath', 'iron', 'will'],
    lore: 'The Oathsworn are remnants of a shattered order — the Covenant of Unbroken Words, who once served as arbiters and enforcers across the known lands. When their fortress-monastery fell to betrayal, the surviving members scattered, each carrying a length of oath-chain forged from the monastery\'s foundation stones. They wander now, bound by the last standing vow: to endure, to protect, to never yield. Each link in their chain represents a promise kept, and with every oath fulfilled, their bodies grow harder, their wills sharper, until some say the eldest Oathsworn are more iron than flesh.',
  },

  {
    id: 'relic-scavenger',
    name: 'Relic Scavenger',
    description:
      'Where others see tombs, you see opportunity. Where others hear the wailing of the restless dead, you hear the clink of ancient artifacts waiting to be liberated. You have spent years crawling through collapsed burial complexes, prying open sealed chambers, and outwitting the traps left by cultivators who wanted their treasures to follow them into the afterlife. Your hands are quick, your eyes are sharp, and you have developed an uncanny sense for objects that still hold power.',
    tags: ['relic', 'dust', 'cunning', 'scavenger', 'tomb'],
    startingTraits: ['tomb-sense'],
    startingMethods: ['relic-attunement'],
    startingItems: ['relic-shard'],
    startingResources: {
      vitality: 10,
      maxVitality: 10,
      essence: 10,
      maxEssence: 10,
      focus: 12,
      maxFocus: 12,
      stability: 10,
      maxStability: 10,
      momentum: 2,
      reputation: -1,
      materials: {},
    },
    affinities: ['relic', 'dust', 'cunning'],
    lore: 'The tombs of the old cultivators are not empty. They are saturated with residual essence, warded by fading but still-lethal formations, and populated by things that were sealed inside for very good reasons. Most who enter never return. The Relic Scavengers are the exceptions — half thief, half archaeologist, all survivor. They trade in the detritus of dead powers, and in doing so, they occasionally stumble upon something that changes them. A relic held too long begins to whisper. A tomb entered too often begins to feel like home. The best scavengers know when to let go of a find. The greatest ones never do.',
  },
];
