import type { SceneDef } from '../engine/types';

export const scenes: SceneDef[] = [
  {
    id: 'crossroads',
    name: 'The Crossroads',
    description: 'Fog curls around a junction of ancient paths, each worn smooth by centuries of passage. Standing stones mark the cardinal directions, their surfaces etched with symbols that seem to shift when viewed from the corner of your eye. The air is heavy with the scent of peat and something older — the mineral tang of buried things.',
    tags: ['crossroads', 'hub', 'moor'],
    region: 'ashenmoor',
    conditions: [],
    onEnter: [],
    choices: [
      {
        id: 'meditate-crossroads',
        text: 'Meditate at the crossroads, drawing on the ambient energy.',
        conditions: [],
        effects: [
          { type: 'add_resource', target: 'essence', value: 10 },
          { type: 'advance_time', value: 1 },
          { type: 'narrative_log', value: 'You sit among the standing stones and breathe. The moor exhales with you.' },
        ],
        resultText: 'The ambient death-essence of the moor flows into you, cold and clarifying. When you open your eyes, the fog has shifted.',
        tags: ['cultivation', 'rest'],
      },
    ],
    exits: [
      { targetScene: 'barrow-entrance', text: 'Follow the northern path toward the ancient barrows.', conditions: [] },
      { targetScene: 'ruined-chapel', text: 'Take the eastern track toward the ruined chapel.', conditions: [] },
      { targetScene: 'moorland-village', text: 'Head south toward the distant lights of the village.', conditions: [] },
      { targetScene: 'bone-field', text: 'Cross the western moor toward the old battlefield.', conditions: [] },
      { targetScene: 'wardens-watch', text: 'Climb the hill toward the Warden\'s Watch outpost.', conditions: [] },
      { targetScene: 'blood-hollow', text: 'Seek the hidden Blood Hollow.', conditions: [{ type: 'world_flag', target: 'blood-hollow-discovered', value: true }] },
      { targetScene: 'whispering-barrow', text: 'Descend into the Whispering Barrow.', conditions: [{ type: 'world_flag', target: 'whispering-barrow-discovered', value: true }] },
      { targetScene: 'crimson-embassy', text: 'Approach the Crimson Court embassy.', conditions: [{ type: 'has_trait', target: 'noble-blood' }] },
      { targetScene: 'shadow-threshold', text: 'Step toward the place where shadows gather.', conditions: [{ type: 'has_method', target: 'shadow-walk' }] },
    ],
    repeatable: true,
  },
  {
    id: 'barrow-entrance',
    name: 'Barrow Entrance',
    description: 'A mound of earth and stone rises from the moor like the back of some buried leviathan. The entrance is a dark mouth framed by carved lintels, the symbols worn but still legible to those who know the old tongues. Cold air breathes outward from the depths, carrying whispers that might be wind or might be something else entirely.',
    tags: ['barrow', 'death', 'exploration'],
    region: 'ashenmoor',
    conditions: [],
    onEnter: [],
    choices: [
      {
        id: 'enter-barrow',
        text: 'Enter the barrow and search for remains.',
        conditions: [],
        effects: [
          { type: 'add_item', target: 'ancient-bone-fragment', value: 1 },
          { type: 'add_corruption', value: 1 },
        ],
        resultText: 'You descend into the cold dark. Among the niches and collapsed chambers, you find bone fragments that still hum with residual essence.',
        tags: ['exploration', 'death'],
      },
      {
        id: 'study-runes',
        text: 'Study the carved runes on the lintel stones.',
        conditions: [{ type: 'min_resource', target: 'focus', value: 20 }],
        effects: [
          { type: 'set_world_flag', target: 'barrow-lore', value: true },
          { type: 'add_resource', target: 'focus', value: -5 },
          { type: 'add_path_depth', value: 1 },
        ],
        resultText: 'The runes resolve into meaning: burial wards, passage prayers, and beneath them, older symbols that describe cultivation techniques lost to the living world.',
        tags: ['study', 'lore'],
      },
      {
        id: 'call-dead',
        text: 'Call to the spirits within.',
        conditions: [{ type: 'has_method', target: 'spirit-communion' }],
        effects: [
          { type: 'set_world_flag', target: 'spirit-ally', value: true },
          { type: 'add_resource', target: 'stability', value: -5 },
          { type: 'add_resource', target: 'essence', value: 15 },
        ],
        resultText: 'Your voice echoes into the barrow and something answers — not with words, but with a pressure against your mind. A spirit acknowledges you.',
        tags: ['spirit', 'communion'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'ruined-chapel',
    name: 'Ruined Chapel',
    description: 'The chapel lists to one side like a drunk trying to maintain dignity. Its stained glass is mostly shattered, but fragments still catch what little light the moor provides, casting sickly prismatic patterns across the stone floor. The altar remains intact — a slab of black basalt that radiates a faint warmth entirely at odds with its appearance.',
    tags: ['chapel', 'sanctity', 'ruin'],
    region: 'ashenmoor',
    conditions: [],
    onEnter: [],
    choices: [
      {
        id: 'pray-altar',
        text: 'Pray at the black altar.',
        conditions: [],
        effects: [
          { type: 'add_stability', value: 10 },
          { type: 'add_resource', target: 'focus', value: 5 },
        ],
        resultText: 'You kneel before the altar. Whether anything listens is unclear, but your spirit steadies and your mind clears.',
        tags: ['sanctity', 'rest'],
      },
      {
        id: 'search-relics',
        text: 'Search the rubble for relics.',
        conditions: [],
        effects: [
          { type: 'add_item', target: 'relic-shard', value: 1 },
          { type: 'add_resource', target: 'momentum', value: 2 },
        ],
        resultText: 'Beneath a collapsed pillar, your fingers close around something that pulses with faint warmth — a shard of something once whole and powerful.',
        tags: ['exploration', 'relic'],
      },
      {
        id: 'confront-spirit',
        text: 'Confront the lingering spirit in the nave.',
        conditions: [{ type: 'min_rank', value: 2 }],
        effects: [
          { type: 'damage', value: 10 },
          { type: 'add_resource', target: 'essence', value: 25 },
          { type: 'add_resource', target: 'reputation', value: 2 },
        ],
        resultText: 'The spirit lashes out in cold fury, but you endure it. As it dissipates, its essence flows into you — decades of accumulated power released in a single exhalation.',
        tags: ['combat', 'spirit'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'moorland-village',
    name: 'Moorland Village',
    description: 'A cluster of stone cottages hunkers against the moor wind, smoke rising from chimneys in thin grey threads. The villagers watch you with the wariness of people who have learned that strangers on the moor usually bring trouble. A small market square offers meager goods, and the tavern door stands ajar.',
    tags: ['village', 'social', 'trade'],
    region: 'ashenmoor',
    conditions: [],
    onEnter: [],
    choices: [
      {
        id: 'trade-village',
        text: 'Trade with the local merchants.',
        conditions: [],
        effects: [
          { type: 'add_item', target: 'bone-dust', value: 3 },
          { type: 'add_resource', target: 'reputation', value: 1 },
        ],
        resultText: 'The merchants are cautious but willing. You acquire bone dust — a common commodity on the moor, useful for cultivation and crafting alike.',
        tags: ['trade', 'social'],
      },
      {
        id: 'seek-rumors',
        text: 'Buy a round at the tavern and listen for rumors.',
        conditions: [],
        effects: [
          { type: 'set_world_flag', target: 'blood-hollow-discovered', value: true },
          { type: 'set_world_flag', target: 'whispering-barrow-discovered', value: true },
          { type: 'narrative_log', value: 'You learn of a hidden hollow where blood seeps from the earth, and a barrow where the dead still whisper.' },
        ],
        resultText: 'Ale loosens tongues. A hunter speaks of a hollow where the ground bleeds, and an old woman warns of a barrow where the whispers never stop.',
        tags: ['social', 'lore'],
      },
      {
        id: 'offer-rites',
        text: 'Offer to perform death rites for the recently departed.',
        conditions: [{ type: 'has_method', target: 'death-rite-officiant' }],
        effects: [
          { type: 'add_faction_rep', target: 'ashen-veil', value: 5 },
          { type: 'add_resource', target: 'reputation', value: 3 },
          { type: 'add_resource', target: 'essence', value: 10 },
        ],
        resultText: 'The villagers accept gratefully. You perform the rites with practiced precision, and the dead settle more easily. Word of your service will reach the Order.',
        tags: ['ritual', 'social', 'death'],
      },
      {
        id: 'intimidate-village',
        text: 'Project your dread presence to demand tribute.',
        conditions: [{ type: 'has_method', target: 'dread-presence' }],
        effects: [
          { type: 'add_item', target: 'grave-iron', value: 2 },
          { type: 'add_faction_rep', target: 'hollow-watch', value: -3 },
          { type: 'add_corruption', value: 2 },
        ],
        resultText: 'The villagers blanch and comply, pressing grave iron ingots into your hands with trembling fingers. Word of this will reach the Watch.',
        tags: ['social', 'intimidation'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'blood-hollow',
    name: 'The Blood Hollow',
    description: 'Hidden in a fold of the moor, this depression in the earth is floored with dark red clay from which crimson liquid seeps in slow, rhythmic pulses — as if the land itself has a heartbeat. The air is thick and warm, tasting of copper and old power. Ancient trees ring the hollow, their roots stained permanently red.',
    tags: ['blood', 'ritual', 'hidden'],
    region: 'ashenmoor',
    conditions: [{ type: 'world_flag', target: 'blood-hollow-discovered', value: true }],
    onEnter: [],
    choices: [
      {
        id: 'drink-pool',
        text: 'Drink from the blood pool.',
        conditions: [],
        effects: [
          { type: 'add_resource', target: 'essence', value: 30 },
          { type: 'add_corruption', value: 5 },
          { type: 'add_tag', target: 'blood-tasted' },
        ],
        resultText: 'The liquid is warm and tastes of iron and lightning. Power floods through you — raw, unrefined, and tinged with something that whispers at the edges of your consciousness.',
        tags: ['blood', 'cultivation'],
      },
      {
        id: 'blood-ritual',
        text: 'Perform a blood inscription ritual at the pool.',
        conditions: [{ type: 'has_method', target: 'blood-inscription' }],
        effects: [
          { type: 'add_title', target: 'blood-drinker' },
          { type: 'add_resource', target: 'essence', value: 20 },
          { type: 'add_corruption', value: 3 },
        ],
        resultText: 'You inscribe sigils around the pool in your own blood. The pool responds, recognizing a kindred practice. The title of Blood Drinker settles upon you like a crimson mantle.',
        tags: ['blood', 'ritual'],
      },
      {
        id: 'study-hollow',
        text: 'Study the phenomenon carefully.',
        conditions: [],
        effects: [
          { type: 'add_path_depth', value: 1 },
          { type: 'add_resource', target: 'focus', value: -5 },
        ],
        resultText: 'You observe the pulse pattern, noting how it aligns with deeper geological rhythms. Understanding deepens your connection to your path.',
        tags: ['study', 'cultivation'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'wardens-watch',
    name: "Warden's Watch",
    description: 'The outpost sits atop a rocky prominence, its walls built from the same grey stone as the moor itself. Iron lanterns burn with steady blue flame along the battlements. Wardens in heavy coats patrol with deliberate discipline, their oath-chains clinking softly. This is the Hollow Watch — guardians of the boundary between the living and the dead.',
    tags: ['outpost', 'oath', 'military'],
    region: 'ashenmoor',
    conditions: [],
    onEnter: [],
    choices: [
      {
        id: 'request-audience',
        text: 'Request an audience with the watch commander.',
        conditions: [],
        effects: [
          { type: 'add_faction_rep', target: 'hollow-watch', value: 3 },
          { type: 'add_resource', target: 'reputation', value: 1 },
        ],
        resultText: 'The commander receives you with gruff courtesy. Your willingness to approach openly earns a measure of respect.',
        tags: ['social', 'faction'],
      },
      {
        id: 'swear-oath',
        text: 'Swear an oath at the binding stone.',
        conditions: [],
        effects: [
          { type: 'add_trait', target: 'oathbound' },
          { type: 'add_stability', value: 10 },
          { type: 'add_faction_rep', target: 'hollow-watch', value: 5 },
        ],
        resultText: 'You place your hand on the binding stone and speak the words. The oath settles into your bones like iron cooling in a mold. You are bound.',
        tags: ['oath', 'binding'],
      },
      {
        id: 'challenge-warden',
        text: 'Challenge a warden to a test of arms.',
        conditions: [{ type: 'min_rank', value: 2 }],
        effects: [
          { type: 'damage', value: 15 },
          { type: 'add_resource', target: 'momentum', value: 10 },
          { type: 'add_resource', target: 'reputation', value: 3 },
        ],
        resultText: 'The warden fights with oath-forged precision. You take hits, but you give them back. Win or lose, you have earned respect through combat.',
        tags: ['combat', 'oath'],
      },
      {
        id: 'spy-watch',
        text: 'Use shadow walk to observe their operations unseen.',
        conditions: [{ type: 'has_method', target: 'shadow-walk' }],
        effects: [
          { type: 'set_world_flag', target: 'warden-intel', value: true },
          { type: 'add_resource', target: 'essence', value: -10 },
        ],
        resultText: 'Wrapped in shadow, you observe patrol routes, supply stores, and the strange rituals the wardens perform at midnight. Valuable intelligence.',
        tags: ['stealth', 'shadow'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'bone-field',
    name: 'The Bone Field',
    description: 'An ancient battlefield where the dead were never properly buried. Bones protrude from the peaty earth like pale fingers reaching for a sky they will never touch. The silence here is profound — even the wind seems to avoid this place. Occasionally, a bone shifts of its own accord, settling deeper or rising higher as the moor breathes.',
    tags: ['bone', 'death', 'battlefield'],
    region: 'ashenmoor',
    conditions: [],
    onEnter: [],
    choices: [
      {
        id: 'harvest-bones',
        text: 'Carefully harvest bones from the field.',
        conditions: [],
        effects: [
          { type: 'add_item', target: 'ancient-bone-fragment', value: 3 },
          { type: 'add_corruption', value: 1 },
        ],
        resultText: 'You select bones that still resonate with essence — femurs from warriors, vertebrae from cultivators. Each one hums faintly in your hands.',
        tags: ['gathering', 'bone'],
      },
      {
        id: 'ossuary-med-field',
        text: 'Perform ossuary meditation among the remains.',
        conditions: [{ type: 'has_method', target: 'ossuary-meditation' }],
        effects: [
          { type: 'add_resource', target: 'essence', value: 20 },
          { type: 'add_path_depth', value: 1 },
          { type: 'add_resource', target: 'focus', value: -10 },
        ],
        resultText: 'Surrounded by the ancient dead, you sink into meditation. Their residual essence flows into you like a cold river. Your path deepens.',
        tags: ['cultivation', 'bone'],
      },
      {
        id: 'raise-construct',
        text: 'Attempt to raise a bone construct from the remains.',
        conditions: [
          { type: 'has_method', target: 'bone-shaping' },
          { type: 'min_rank', value: 2 },
        ],
        effects: [
          { type: 'add_companion', target: 'bone-construct' },
          { type: 'add_resource', target: 'essence', value: -20 },
          { type: 'add_corruption', value: 3 },
        ],
        resultText: 'Bones rise and interlock under your will, assembling into a skeletal form that regards you with empty eye sockets. It awaits your command.',
        tags: ['craft', 'bone', 'companion'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'whispering-barrow',
    name: 'The Whispering Barrow',
    description: 'Unlike the other barrows, this one is alive with sound — a constant murmur of voices speaking in languages that predate writing. The interior is warm despite the depth, and ghostly lights drift between the burial niches. The dead here are not resting. They are waiting.',
    tags: ['spirit', 'barrow', 'communion'],
    region: 'ashenmoor',
    conditions: [{ type: 'world_flag', target: 'whispering-barrow-discovered', value: true }],
    onEnter: [],
    choices: [
      {
        id: 'commune-dead',
        text: 'Commune with the ancient spirits.',
        conditions: [{ type: 'has_method', target: 'spirit-communion' }],
        effects: [
          { type: 'add_method_mastery', target: 'spirit-communion', value: 1 },
          { type: 'add_resource', target: 'essence', value: 15 },
          { type: 'add_resource', target: 'stability', value: -5 },
        ],
        resultText: 'The spirits press close, sharing fragments of knowledge that taste like ash and starlight. Your understanding of communion deepens.',
        tags: ['spirit', 'cultivation'],
      },
      {
        id: 'bind-spirit',
        text: 'Attempt to bind a spirit to your service.',
        conditions: [],
        effects: [
          { type: 'damage', value: 10 },
          { type: 'add_stability', value: -10 },
          { type: 'add_tag', target: 'spirit-bound' },
          { type: 'add_resource', target: 'essence', value: 10 },
        ],
        resultText: 'The binding is violent and painful. A spirit screams as your will clamps around it. It submits, but resentfully. The other spirits fall silent.',
        tags: ['spirit', 'binding'],
      },
      {
        id: 'plunder-tomb',
        text: 'Plunder the burial offerings.',
        conditions: [],
        effects: [
          { type: 'add_item', target: 'tomb-jade', value: 2 },
          { type: 'add_faction_rep', target: 'ashen-veil', value: -5 },
          { type: 'add_corruption', value: 2 },
        ],
        resultText: 'You take what the dead no longer need — jade amulets placed with care by mourners long turned to dust themselves. The spirits howl in outrage.',
        tags: ['exploration', 'theft'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'crimson-embassy',
    name: 'Crimson Court Embassy',
    description: 'A pavilion of dark red silk stretched over iron frames, incongruously luxurious against the bleak moor. Servants in crimson livery move with the practiced grace of the blood-cultivated. The air smells of wine and iron. This is where the Crimson Court extends its influence beyond the cities — with velvet gloves over iron fists.',
    tags: ['blood', 'noble', 'faction'],
    region: 'ashenmoor',
    conditions: [{ type: 'has_trait', target: 'noble-blood' }],
    onEnter: [],
    choices: [
      {
        id: 'seek-patronage',
        text: 'Seek patronage from the Court representative.',
        conditions: [],
        effects: [
          { type: 'add_faction_rep', target: 'crimson-court', value: 5 },
          { type: 'add_item', target: 'congealed-blood-crystal', value: 2 },
        ],
        resultText: 'The representative examines your bloodline with practiced eye and nods. Resources are provided — an investment in your potential. The Court always expects returns.',
        tags: ['social', 'blood'],
      },
      {
        id: 'attend-rite',
        text: 'Attend the evening blood rite.',
        conditions: [],
        effects: [
          { type: 'add_resource', target: 'essence', value: 20 },
          { type: 'add_corruption', value: 3 },
          { type: 'add_path_depth', value: 1 },
        ],
        resultText: 'The rite is beautiful and disturbing — blood drawn, shared, and transmuted in patterns that predate the Court itself. Power flows freely, but at a cost that is not immediately apparent.',
        tags: ['ritual', 'blood', 'cultivation'],
      },
      {
        id: 'trade-crystals',
        text: 'Trade blood crystals for social influence.',
        conditions: [{ type: 'has_item', target: 'congealed-blood-crystal' }],
        effects: [
          { type: 'remove_item', target: 'congealed-blood-crystal', value: 1 },
          { type: 'add_resource', target: 'reputation', value: 5 },
        ],
        resultText: 'Blood crystals are the currency of the Court. Your offering is accepted, and your name is spoken with slightly more respect in crimson halls.',
        tags: ['trade', 'blood'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'shadow-threshold',
    name: 'The Shadow Threshold',
    description: 'Reality frays here like old cloth. The air shimmers between solid and translucent, and your shadow behaves independently — reaching toward a point in space where the darkness is absolute and total. This is a crossing point, a place where the membrane between the material world and the shadow realm is thin enough to breach.',
    tags: ['shadow', 'liminal', 'passage'],
    region: 'ashenmoor',
    conditions: [{ type: 'has_method', target: 'shadow-walk' }],
    onEnter: [],
    choices: [
      {
        id: 'step-through',
        text: 'Step through the threshold into the Ossuary Depths.',
        conditions: [],
        effects: [
          { type: 'unlock_region', target: 'ossuary-depths' },
          { type: 'add_resource', target: 'essence', value: -15 },
          { type: 'add_corruption', value: 2 },
        ],
        resultText: 'You step into the absolute dark and emerge elsewhere — deep underground, in a chamber where the walls are made of bones arranged with architectural precision.',
        tags: ['passage', 'shadow'],
        nextScene: 'ossuary-antechamber',
      },
      {
        id: 'observe-shadows',
        text: 'Observe the shadow patterns without crossing.',
        conditions: [],
        effects: [
          { type: 'add_resource', target: 'essence', value: 10 },
          { type: 'add_path_depth', value: 1 },
        ],
        resultText: 'You watch the shadows dance and learn their language — the way darkness flows, pools, and speaks. Your understanding of the liminal deepens.',
        tags: ['study', 'shadow'],
      },
      {
        id: 'anchor-self',
        text: 'Anchor yourself against the pull of the shadow realm.',
        conditions: [],
        effects: [
          { type: 'add_stability', value: 15 },
        ],
        resultText: 'You plant your feet and will yourself solid. The shadow realm recedes, and you feel more grounded, more certain of your place in the material world.',
        tags: ['cultivation', 'stability'],
      },
    ],
    exits: [
      { targetScene: 'crossroads', text: 'Return to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'ossuary-antechamber',
    name: 'Ossuary Antechamber',
    description: 'The walls are made of bones — thousands of them, arranged in patterns that are simultaneously decorative and functional. Femurs form arches. Skulls line niches like silent sentinels. The air is dry and tastes of ancient dust. Faint luminescence emanates from the bone formations themselves, casting everything in a pale, ghostly light.',
    tags: ['bone', 'underground', 'ossuary'],
    region: 'ossuary-depths',
    conditions: [],
    onEnter: [
      { type: 'add_corruption', value: 1 },
    ],
    choices: [
      {
        id: 'descend-deeper',
        text: 'Descend deeper into the ossuary.',
        conditions: [],
        effects: [],
        resultText: 'You follow the bone-lined passages downward, the formations growing more elaborate and the air growing colder with each step.',
        tags: ['exploration'],
        nextScene: 'ossuary-heart',
      },
      {
        id: 'study-carvings',
        text: 'Study the cultivation diagrams carved into the walls.',
        conditions: [],
        effects: [
          { type: 'set_world_flag', target: 'ossuary-lore', value: true },
          { type: 'add_resource', target: 'focus', value: 10 },
          { type: 'add_path_depth', value: 1 },
        ],
        resultText: 'The diagrams depict cultivation techniques from a civilization that predates all known traditions. Your understanding expands painfully, like a mind stretching to contain something too large.',
        tags: ['study', 'lore'],
      },
      {
        id: 'camp-ossuary',
        text: 'Set up camp and rest.',
        conditions: [],
        effects: [
          { type: 'add_resource', target: 'vitality', value: 20 },
          { type: 'add_stability', value: 10 },
          { type: 'advance_time', value: 1 },
        ],
        resultText: 'You rest among the bones. They are surprisingly comfortable company — silent, patient, and entirely without judgment. Your body recovers, though strange dreams visit you.',
        tags: ['rest'],
      },
    ],
    exits: [
      { targetScene: 'shadow-threshold', text: 'Return to the surface through the shadow threshold.', conditions: [] },
      { targetScene: 'crossroads', text: 'Find your way back to the crossroads.', conditions: [] },
    ],
    repeatable: true,
  },
  {
    id: 'ossuary-heart',
    name: 'The Ossuary Heart',
    description: 'The deepest chamber opens into a cathedral of bone. Ribs arch overhead like the vaulting of some impossible church. At the center stands a throne carved from a single massive skull — perhaps a dragon, perhaps something older. The essence concentration here is overwhelming, pressing against your skin like deep water. This is a place of power. This is where things change.',
    tags: ['bone', 'power', 'breakthrough'],
    region: 'ossuary-depths',
    conditions: [],
    onEnter: [
      { type: 'add_corruption', value: 2 },
      { type: 'add_resource', target: 'essence', value: 10 },
    ],
    choices: [
      {
        id: 'attempt-breakthrough-ossuary',
        text: 'Attempt a breakthrough in this place of concentrated power.',
        conditions: [{ type: 'min_rank', value: 1 }],
        effects: [
          { type: 'trigger_breakthrough' },
        ],
        resultText: 'You sit upon the cold bone floor and turn your cultivation inward. The ambient power of the ossuary presses against your gates, demanding entry.',
        tags: ['breakthrough', 'cultivation'],
      },
      {
        id: 'claim-throne',
        text: 'Claim the bone throne.',
        conditions: [
          { type: 'has_path', target: 'bone-architect' },
          { type: 'min_rank', value: 3 },
        ],
        effects: [
          { type: 'add_title', target: 'bone-collector' },
          { type: 'add_resource', target: 'essence', value: 50 },
          { type: 'add_tag', target: 'throne-claimed' },
        ],
        resultText: 'You ascend the steps and sit upon the skull throne. The bones of the ossuary shudder in recognition. A title settles upon you — ancient, heavy, and absolute.',
        tags: ['bone', 'power', 'title'],
      },
      {
        id: 'commune-ossuary',
        text: 'Commune with the ossuary itself.',
        conditions: [],
        effects: [
          { type: 'add_resource', target: 'essence', value: 40 },
          { type: 'add_stability', value: -15 },
          { type: 'add_corruption', value: 3 },
        ],
        resultText: 'You open your mind to the ossuary and it responds — not with words, but with a flood of impressions spanning millennia. The knowledge is intoxicating and destabilizing in equal measure.',
        tags: ['communion', 'bone'],
      },
    ],
    exits: [
      { targetScene: 'ossuary-antechamber', text: 'Ascend back to the antechamber.', conditions: [] },
    ],
    repeatable: true,
  },
];
